# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 11:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True, verbose_name=b'Job review')),
                ('is_selected', models.BooleanField(verbose_name=b'Selected?')),
                ('progress', models.IntegerField(verbose_name=b'Number of tests passed')),
                ('jaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JAF', verbose_name=b'Job application')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_number', models.IntegerField(choices=[(0, b'One page'), (1, b'Two page Tech'), (2, b'One page Nontech'), (3, b'CV')], verbose_name=b'Resume number')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'Student ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Full name')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')], verbose_name=b'Phone number')),
                ('reg_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1958), django.core.validators.MaxValueValidator(2018)], verbose_name=b'Registration year')),
                ('cpi', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name=b'CPI')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department', verbose_name=b'Department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Program', verbose_name=b'Program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name=b'Resume of'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name=b'Applicant'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('student', 'jaf')]),
        ),
    ]
