# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together=set([('student', 'resume_number')]),
        ),
    ]
