# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20171104_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_selected',
            field=models.BooleanField(verbose_name='Selected?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='jaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JAF', verbose_name='Job application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='progress',
            field=models.IntegerField(verbose_name='Number of tests passed'),
        ),
        migrations.AlterField(
            model_name='application',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Job review'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Applicant'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_number',
            field=models.IntegerField(choices=[(0, 'One page'), (1, 'Two page Tech'), (2, 'One page Nontech'), (3, 'CV')], verbose_name='Resume number'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Resume of'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpi',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='CPI'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1958), django.core.validators.MaxValueValidator(2018)], verbose_name='Registration year'),
        ),
    ]
