# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171104_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume_verified',
            field=models.BooleanField(default=False, verbose_name='Resume verified?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Selected?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Number of tests passed'),
        ),
    ]
