# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20171104_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False, verbose_name=b'Verification Status'),
            preserve_default=False,
        ),
    ]
