# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='verified',
        ),
    ]
