# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
