# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Student'),
        ),
    ]
