# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 11:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi_cutoff', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name=b'CPI')),
                ('stipend', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Compensation')),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name=b'Unit')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department', verbose_name=b'Department')),
                ('jaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JAF', verbose_name=b'JAF')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Program', verbose_name=b'Program')),
            ],
        ),
        migrations.CreateModel(
            name='JAFTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Test venue/URL')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name=b'Test time')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Test details')),
                ('duration', models.FloatField(verbose_name=b'Test duration (minutes)')),
                ('jaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JAF', verbose_name=b'JAF')),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name=b'Test type')),
            ],
        ),
        migrations.AddField(
            model_name='jaftest',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.TestType', verbose_name=b'Test type'),
        ),
    ]
