# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20171104_1142'),
        ('company', '0002_auto_20171104_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaftest',
            name='test_number',
            field=models.IntegerField(default=-1, verbose_name=b'Test no.'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eligibility',
            unique_together=set([('department', 'jaf', 'program')]),
        ),
        migrations.AlterUniqueTogether(
            name='jaftest',
            unique_together=set([('test_number', 'jaf')]),
        ),
    ]
