# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20171104_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='cpi_cutoff',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='CPI'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='currency',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='jaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JAF', verbose_name='JAF'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='stipend',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Compensation'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='accomodation',
            field=models.TextField(verbose_name='Accomodation details'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='description',
            field=models.TextField(verbose_name='Job description'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7)], verbose_name='Internship duration (days)'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='JAF no.'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='job_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1958), django.core.validators.MaxValueValidator(2018)], verbose_name='Registration year'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='Other details'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='posting',
            field=models.CharField(max_length=50, verbose_name='Place of posting'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='profile',
            field=models.CharField(max_length=50, verbose_name='Job profile'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='requirements',
            field=models.TextField(verbose_name='Job requirements'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='resume_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Resume no. wanted'),
        ),
        migrations.AlterField(
            model_name='jaftest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Test details'),
        ),
        migrations.AlterField(
            model_name='jaftest',
            name='duration',
            field=models.FloatField(verbose_name='Test duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='jaftest',
            name='jaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JAF', verbose_name='JAF'),
        ),
        migrations.AlterField(
            model_name='jaftest',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Test venue/URL'),
        ),
        migrations.AlterField(
            model_name='jaftest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test time'),
        ),
        migrations.AlterField(
            model_name='jaftest',
            name='test_number',
            field=models.IntegerField(verbose_name='Test no.'),
        ),
        migrations.AlterField(
            model_name='jaftest',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.TestType', verbose_name='Test type'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Test type'),
        ),
    ]
