# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20171104_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaftest',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last date to sign'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='currency',
            field=models.CharField(default='INR', max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='Unit'),
        ),
    ]
