# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 13:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20171104_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaf',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name=b'Internship duration (weeks)'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='job_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1958), django.core.validators.MaxValueValidator(2018)], verbose_name=b'Internship year'),
        ),
    ]
