# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 20:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20171106_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaf',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Internship duration (weeks)'),
        ),
        migrations.AlterField(
            model_name='jaf',
            name='job_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1958), django.core.validators.MaxValueValidator(2018)], verbose_name='Internship year'),
        ),
    ]
