# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Job review')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Selected?')),
                ('progress', models.IntegerField(default=0, verbose_name='Number of tests passed')),
                ('jaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JAF', verbose_name='Job application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='Applicant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('student', 'jaf')]),
        ),
    ]
